start: start
nodes:
  - tag: start
    type: core.trim

  - tag: trimmed
    type: processors.taggers.Tagger

  - tag: error
    type: core.to_uppercase

  - tag: warn
    type: core.to_snakecase

  - tag: general
    type: core.to_uppercase

  - tag: end
    type: processors.output.terminal
