start: split_lines   # <-- new field
nodes:
  - name: split_lines
    type: processors.fanout.SplitLines
    routes:
      split: snake_case

  - name: snake_case
    type: processors.snake.snake_processor
    routes:
      snake: to_upper

  - name: to_upper
    type: processors.upper.upper_processor
    routes:
      uppercase: join_lines

  - name: join_lines
    type: processors.fanin.JoinEveryTwoLines
    routes:
      joined: count_lines

  - name: count_lines
    type: processors.base.LineCounter
    routes: {}
