start: trim
nodes:
  - name: trim
    type: core.trim
    routes:
      trimmed: classify

  - name: classify
    type: processors.taggers.TagError
    routes:
      error: handle_error
      general: check_warn

  - name: check_warn
    type: processors.taggers.TagWarn
    routes:
      warn: handle_warning
      general: handle_general

  - name: handle_error
    type: core.to_uppercase
    routes: {}

  - name: handle_warning
    type: core.to_snakecase
    routes: {}

  - name: handle_general
    type: core.to_uppercase
    routes: {}
