services:
  db:
    image: mariadb:12.0-ubi10
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  python_app:
    image: python:3.13
    container_name: python_script
    command: sh -c "apt-get update && apt-get install -y default-mysql-client && \
                    pip install mysql-connector-python && \
                    until mysqladmin ping -h db -u myuser -pmypass --silent; do \
                      echo 'Waiting for database...'; sleep 2; \
                    done && python emp_logger.py"
    volumes:
      - ./scripts:/app
      - ./data:/data
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    restart: "no"


networks:
  app_network:
    driver: bridge
